Repository TheHive-Project/Cortex-Analyzers, pull requests merged in 2024-10, with the labels that each got.

#1121 Update of NERD analyzer
  analyzers/NERD/README.md
  analyzers/NERD/nerd.json
  analyzers/NERD/nerd_analyzer.py
Labels: category:enhancement

#1225 Fixes and added features to Defender for endpoints responder
  responders/MSDefenderEndpoints/Dockerfile
  responders/MSDefenderEndpoints/MSDefenderEndpoints.py
  responders/MSDefenderEndpoints/MSDefenderEndpoints_AutoInvestigation.json
  responders/MSDefenderEndpoints/MSDefenderEndpoints_Isolate.json
  responders/MSDefenderEndpoints/MSDefenderEndpoints_PushIOCAlert.json
  responders/MSDefenderEndpoints/MSDefenderEndpoints_PushIOCBlock.json
  responders/MSDefenderEndpoints/MSDefenderEndpoints_RestrictAppExecution.json
  responders/MSDefenderEndpoints/MSDefenderEndpoints_UnRestrictAppExecution.json
  responders/MSDefenderEndpoints/MSDefenderEndpoints_Unisolate.json
  responders/MSDefenderEndpoints/MSDefenderEndpoints_VirusScan.json
  responders/MSDefenderEndpoints/README.md
Labels: analyzer-update

#1117 [FIX] HybridAnalysis API V2
  analyzers/HybridAnalysis/HybridAnalysis_GetReport.json
  analyzers/HybridAnalysis/HybridAnalysis_analyzer.py
Labels: category:enhancement

#1157 Search users in Okta.
  analyzers/OktaUserLookup/OktaUserLookup.json
  analyzers/OktaUserLookup/oktauserlookup_analyzer.py
  analyzers/OktaUserLookup/requirements.txt
  thehive-templates/OktaUserLookup_1_0/long.html
  thehive-templates/OktaUserLookup_1_0/short.html
Labels: category:new-analyzer

#1058 DNSdumpster analyzer. Initial commit.
  analyzers/DNSdumpster/DNSdumpster.json
  analyzers/DNSdumpster/README.md
  analyzers/DNSdumpster/dnsdumpster.py
  analyzers/DNSdumpster/requirements.txt
Labels: category:new-analyzer

#1055 cortexutils not installed in RT4 Responder Docker Image
  responders/RT4/requirements.txt
Labels: category:bugfix

#1053 Netcraft Cortex responder
  responders/Netcraft/Dockerfile
  responders/Netcraft/Netcraft.py
  responders/Netcraft/NetcraftTakedown.json
  responders/Netcraft/README.md
  responders/Netcraft/requirements.txt
Labels: category:new-responder
